export const ETypeDocument = {
  DOCUMENTO_REQUIERE_FIRMA: 'DOCUMENTO_REQUIERE_FIRMA',
  TRAMITE_REENVIADO: 'TRAMITE_REENVIADO',
  TRAMITE_RECIBIDO: 'TRAMITE_RECIBIDO',
  RESPUESTA_RECIBIDA: 'RESPUESTA_RECIBIDA',
  TRAMITE_FIRMADO: 'TRAMITE_FIRMADO',
  TRAMITE_ANULADO: 'TRAMITE_ANULADO',
  OBSERVACION_CREADA: 'OBSERVACION_CREADA',
  OBSERVACION_RESUELTA: 'OBSERVACION_RESUELTA',
} as const;

export type ETypeDocument = (typeof ETypeDocument)[keyof typeof ETypeDocument];
